CU-860payu1a_Develop-Disclosure-Component_Fadhlan-Hasyim
COMPFEST/silicon pull request #10
Opened 2023-01-17 03:28 UTC by fadhlanhasyim

2023-01-17 13:47 UTC, gibranoderenz commented on src/Disclosure/Disclosure.style.tsx
> +    background: rgba(255, 255, 255, 0.1);
ini tambahin `cursor: pointer` aja biar user tau bisa diklik

2023-01-23 02:45 UTC, DJaegerScript requested changes
<img width="497" alt="image" src="https://user-images.githubusercontent.com/85334514/213957724-5f49afd4-85de-40e2-ad1f-ec513a2be493.png">

ditruncate 1 line aja kalo misal string sepanjang ini dalam title

2023-01-23 02:52 UTC, DJaegerScript requested changes
coba tambahin size variant deh kayak `sm, md, lg`

2023-01-23 02:52 UTC, DJaegerScript commented on src/Disclosure/index.tsx
> +  const { title, content } = props
destructure dalam 1 line aja 
```suggestion
const Disclosure: React.FC<DisclosureProps> = ({  title, content }) => {
```

2023-01-23 02:52 UTC, DJaegerScript commented on src/Disclosure/interface.ts
> +  content: string
`content` lebih baik jadi `children` aja, karena gk menutup kemungkinan kalo disclosure itu kontennya image atau rich text

```suggestion
  children: ReactNode
```

2023-01-23 16:46 UTC, fadhlanhasyim commented on src/Disclosure/index.tsx
> +  const { title, content } = props
done

2023-01-23 17:05 UTC, fadhlanhasyim commented on src/Disclosure/interface.ts
> +  content: string
done

2023-01-23 17:05 UTC, fadhlanhasyim commented on src/Disclosure/Disclosure.style.tsx
> +    background: rgba(255, 255, 255, 0.1);
done

2023-02-08 23:11 UTC, DJaegerScript approved these changes

2023-02-08 23:12 UTC, merged