CU_860payua4_Develop-Modal-Component_Yudi-Sabri
COMPFEST/silicon pull request #12
Opened 2023-01-17 03:43 UTC by yudiptr

2023-01-17 12:43 UTC, gibranoderenz commented on src/Modal/Modal.stories.tsx
> +  argTypes: {
di `argTypesnya` tambahin ini aja biar nanti di controlsnya dia ilang kayak di component `Button`
```ts
acceptButton: {
    table: {
        disable: true,
    },
},
cancelButton: {
    table: {
        disable: true,
    },
},
```

2023-01-17 12:46 UTC, gibranoderenz commented on src/Modal/Modal.style.tsx
> +export const HeadingText = styled.p`
![image](https://user-images.githubusercontent.com/70869295/212902379-241e350b-36d6-4a0c-b346-c2f915a5b02e.png)
ini heading dempet gituu kalo teksnya agak panjangan

2023-01-17 13:42 UTC, gibranoderenz approved these changes

2023-01-23 03:36 UTC, DJaegerScript requested changes
- coba bikin size variant kayak (sm, md, lg)
- gap antara heading dan body kejauhan
- dibikin lebih simetris
![image](https://user-images.githubusercontent.com/85334514/213961703-5e9721e1-21ef-4a49-93bd-e58cd9a00157.png)

2023-01-23 03:36 UTC, DJaegerScript commented on src/Modal/index.tsx
> +          <ContentText>{content}</ContentText>
Jadiin children aja, karena gk menetup kemungkinan user bakal pake rich text di sini

2023-01-23 03:36 UTC, DJaegerScript commented on src/Modal/index.tsx
> +        <ImgContainer src={imageUrl}></ImgContainer>
- Image dibikin optional aja
- kasih border radius di image, biar synchron sama modalnya

2023-01-23 03:36 UTC, DJaegerScript commented on src/Modal/interface.ts
> +  content: string
ganti pake children

2023-02-07 23:38 UTC, DJaegerScript requested changes

2023-02-07 23:38 UTC, DJaegerScript commented on src/Modal/index.tsx
> +  ...props
kalo gak kepake gk usah ada

2023-02-07 23:38 UTC, DJaegerScript commented on src/Modal/index.tsx
> +  acceptButton = null,
gak usah dikasih null

2023-02-07 23:38 UTC, DJaegerScript commented on src/Modal/index.tsx
> +  const modContain = useRef(null)
kenapa pake `ref`?

2023-02-07 23:38 UTC, DJaegerScript commented on src/Modal/index.tsx
> +          <ButtonContent variant={variant}>{cancelButton}</ButtonContent>
dibikin conditional, kalo `cancelButton` tidak sama dengan `null` container dari `acceptButton` dibikin full width

2023-02-07 23:38 UTC, DJaegerScript commented on src/Modal/interface.ts
> +  isDisplayed: true | false
kasih aja type `boolean`

2023-02-07 23:38 UTC, DJaegerScript commented on src/Modal/interface.ts
> +  alt: string
dibikin optional

2023-02-07 23:38 UTC, DJaegerScript commented on src/Modal/interface.ts
> +  extends Partial<ModalExtensionProps>,
`ModalExtensionProps` disatuin aja ke `ModalProps` kagak perlu pake extends

2023-02-08 08:03 UTC, yudiptr commented on src/Modal/index.tsx
> +  ...props
ini emang perlu bang, buat refer ke storybook sama handle statenya

2023-02-08 08:04 UTC, yudiptr commented on src/Modal/index.tsx
> +  ...props
ini emang perlu bang, buat distorybooknya

2023-02-08 08:06 UTC, yudiptr commented on src/Modal/index.tsx
> +  const modContain = useRef(null)
done, lupa apus kemarin coba-coba

2023-02-08 08:23 UTC, yudiptr commented on src/Modal/index.tsx
> +          <ButtonContent variant={variant}>{cancelButton}</ButtonContent>
ini gw ada blocker kayaknya deh, buttonnya gamau ngescretch gitu

2023-02-08 09:06 UTC, yudiptr commented on src/Modal/interface.ts
> +  extends Partial<ModalExtensionProps>,
ini perlu untuk storybook sih

2023-02-08 23:07 UTC, DJaegerScript reviewed
`handleState` (currently `onClose`) itu gunanya apa yud? gw kira untuk tutup modal bas user klik overlaynya, makanya gw ganti namanya. Tapi, tadi gw coba click overlaynya gk ketutup dan emg gk ada overlay juga

2023-02-09 04:10 UTC, yudiptr commented
udah disolve bang itu, itu ada Id keapus sama lu jadi pas overlay kepencet gak ke tutup wkkw. udah aman

2023-02-09 04:35 UTC, DJaegerScript requested changes

2023-02-09 04:35 UTC, DJaegerScript commented on src/Modal/index.tsx
> +          const modal = document.getElementById("modal-overlay")
coba pake `name` atau `className`

2023-02-09 05:07 UTC, yudiptr commented on src/Modal/index.tsx
> +          const modal = document.getElementById("modal-overlay")
done bang

2023-02-09 23:27 UTC, DJaegerScript approved these changes

2023-02-09 23:28 UTC, merged