CU-860paytx9_Develop-Toast-Component_Fadhlan-Hasyim
COMPFEST/silicon pull request #15
Opened 2023-01-18 06:18 UTC by fadhlanhasyim

2023-01-22 11:20 UTC, DJaegerScript reviewed
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/85334514/213913067-8fc54c41-333c-4f2f-9fa1-5e2774508d9f.png">

`Controls` tuh bagus kalo lu nunjukin style dari masing masing state, misal nanti kalo dia lagi `error toast` stylenya kayak gimana. 

 Dan jangan taro yang minta input berupa `JSON` di `Controls`

2023-01-22 11:20 UTC, DJaegerScript commented on src/Button/Button.stories.tsx
> +import Button from '.'
ini ngaruh apa, dlan?

2023-01-22 11:20 UTC, DJaegerScript commented on src/Toast/Toast.stories.tsx
> +      <button onClick={useToast({ ...props })}>Tap me!</button>
Example buttonnya bisa pake button silicon gak?

2023-01-22 11:20 UTC, DJaegerScript commented on src/Toast/index.tsx
> +)
icon gk usah taro di component, kalo mau jadi display, taro di stories aja kayak di `button.stories.ts`

2023-01-22 11:20 UTC, DJaegerScript commented on src/index.ts
> +export { Button, Toast, useToast }
ini apa gk kebalik lu penamaannya? kalo menurut gw lebih cocok yang diimport dari `trigger` itu `useToast`. Atau sebenernya disatuin dalam satu file juga gk apa apa yang penting diexport semua

2023-01-22 11:20 UTC, DJaegerScript commented on src/Toast/interface.ts
> +  promise: Promise<unknown>
promise ini buat apa deh?

2023-01-22 18:04 UTC, DJaegerScript requested changes
kayaknya hook toast yang lu buat masih luamyan rumit deh

kalo dari gw, gw mikirnya lu custom style si [Toaster](https://react-hot-toast.com/docs/toaster) trs untuk hooknya, lu tinggal import dari [toast](https://react-hot-toast.com/docs/toast) abis lu import, lu exporrt lagi, biar kesannya user ngeexport dari `compfest-silicon`

nah ini lu pernah nyoba gk?

2023-01-23 06:12 UTC, fadhlanhasyim commented on src/Toast/Toast.stories.tsx
> +      <button onClick={useToast({ ...props })}>Tap me!</button>
done

2023-01-23 06:13 UTC, fadhlanhasyim commented on src/Button/Button.stories.tsx
> +import Button from '.'
done dihapus

2023-01-23 06:26 UTC, fadhlanhasyim commented on src/index.ts
> +export { Button, Toast, useToast }
done disatuin ke dalam index.tsx

2023-01-23 06:27 UTC, fadhlanhasyim commented on src/Toast/index.tsx
> +)
done dipindahkan ke stories

2023-01-23 06:36 UTC, fadhlanhasyim commented on src/Toast/interface.ts
> +  promise: Promise<unknown>
![image](https://user-images.githubusercontent.com/81791118/213978886-17e3f7b8-bc4f-4beb-9ecc-38a7853a48c7.png) ini ji, toastnya nerima promise untuk nentuin state-nya

2023-01-23 07:16 UTC, fadhlanhasyim commented on src/Toast/interface.ts
> +  promise: Promise<unknown>
gajadi ji, gua hapus promisenya

2023-02-04 14:03 UTC, DJaegerScript requested changes
- fix default `useToast`

2023-02-09 23:26 UTC, DJaegerScript approved these changes

2023-02-09 23:26 UTC, merged