CU-860payucd_Develop-Input-Component_Bonaventura-Galang
COMPFEST/silicon pull request #8
Opened 2023-01-17 03:13 UTC by bonaventuragal

2023-01-17 09:05 UTC, gibranoderenz commented on src/Input/Checkbox/Checkbox.style.tsx
> +    border: 1px solid rgba(255, 255, 255, 0.1);
mungkin di sini bisa tambahin `cursor: not-allowed` biar dia disabled nanti

2023-01-17 09:07 UTC, gibranoderenz commented on src/Input/Checkbox/Checkbox.style.tsx
> +      border: 1px solid rgba(255, 255, 255, 0.6);
yang ini bisa nambahin `cursor: pointer` biar usernya tau bisa diklik

2023-01-17 10:56 UTC, gibranoderenz commented on src/Input/Radio/Radio.style.tsx
> +      border: 1px solid rgba(255, 255, 255, 0.6);
ini juga tambahin `cursor: pointer` yak

2023-01-17 10:58 UTC, gibranoderenz commented on src/Input/Radio/Radio.style.tsx
> +    border: 1px solid rgba(255, 255, 255, 0.1);
ini juga tambahin `cursor: not-allowed` yak

2023-01-17 11:39 UTC, gibranoderenz commented on src/Input/Checkbox/index.tsx
> +      <CheckboxDiv onClick={() => checkboxRef.current?.click()}>
ini berarti belum ada yang ngambil value dari checkboxnya ya?

2023-01-18 03:37 UTC, bonaventuragal commented on src/Input/Checkbox/Checkbox.style.tsx
> +    border: 1px solid rgba(255, 255, 255, 0.1);
semua cursor udah yaa [4f32bd7](https://github.com/COMPFEST/silicon/pull/8/commits/4f32bd732d8f6ed1da9a9eab58051bedd1c754ad)

2023-01-19 04:42 UTC, gibranoderenz approved these changes

2023-01-24 01:35 UTC, DJaegerScript requested changes
![image](https://user-images.githubusercontent.com/85334514/214195152-dde0b94d-068f-406b-821f-085962d4c8bf.png)

border/outline checkboxnya pas onHover tolong dihilangin aja

2023-01-24 01:47 UTC, DJaegerScript requested changes
componentnya tolong di exporrt dari `/src/index.ts` biar bisa dipake as library

2023-01-24 01:47 UTC, DJaegerScript commented on src/Input/TextInput/index.tsx
> +          type="text"
lebih baik `type` dijadiin props karena bisa aja dipake untuk password, email, dll

2023-01-25 03:56 UTC, bonaventuragal commented on src/Input/TextInput/index.tsx
> +          type="text"
done

2023-02-07 22:28 UTC, DJaegerScript approved these changes

2023-02-07 22:29 UTC, merged