CU-860payu3p_Develop-Cards-Component_Fadhlan-Hasyim
COMPFEST/silicon pull request #9
Opened 2023-01-17 03:25 UTC by fadhlanhasyim

2023-01-18 16:44 UTC, gibranoderenz approved these changes
thanks dlan mantap

2023-01-24 01:26 UTC, DJaegerScript requested changes

2023-01-24 01:26 UTC, DJaegerScript commented on src/Cards/index.tsx
> +  const { imageUrl, title, body, className, imgClassName, width, height } =
destructurenya dalam 1 line aja

2023-01-24 01:26 UTC, DJaegerScript commented on src/Cards/index.tsx
> +    <Main id="main" className={className} width={width} height={height}>
`id` nya dijadiin props

2023-01-24 01:26 UTC, DJaegerScript commented on src/Cards/interface.ts
> +  height: number
kenapa harus aja ini?

mending dibikin size variant aja

2023-02-04 14:16 UTC, DJaegerScript requested changes
- use `isExpand` props rather than `getElementById` to change styling
- add popup animation

2023-02-09 23:24 UTC, DJaegerScript approved these changes

2023-02-09 23:25 UTC, merged